apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default # singleton
spec:
  subject:
    namespaces:
      matchLabels:
          kubernetes.io/metadata.name: dumbledore
  ingress:
  - name: "deny-all-ingress-from-gryffindor-to-dumbledore"
    action: "Deny"
    from:
    - namespaces:
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: gryffindor
  - name: "deny-all-ingress-from-slytherin-to-dumbledore"
    action: "Deny"
    from:
    - namespaces:
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: slytherin
