apiVersion: policy.networking.k8s.io/v1alpha1
kind: BaselineAdminNetworkPolicy
metadata:
  name: default # singleton
spec:
  subject:
    namespaces: {}
  ingress:
  - name: "deny-all-egress-to-forbidden-forest"
    action: "Deny"
    to:
    - namespaces:
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: forbidden-forest
