apiVersion: v1
kind: Namespace
metadata:
  name: professors
  labels:
    role: supervisor
    owner: minerva-mcgonagall
---
apiVersion: v1
kind: Namespace
metadata:
  name: gryffindor
  labels:
    house: gryffindor
    owner: harry-potter
---
apiVersion: v1
kind: Namespace
metadata:
  name: slytherin
  labels:
    house: slytherin
    owner: draco-malfoy
---
apiVersion: v1
kind: Namespace
metadata:
  name: forbidden-forest
  labels:
    type: forbidden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minerva-mcgonagall
  namespace: professors
spec:
  selector:
    matchLabels:
      owner: minerva-mcgonagall
  replicas: 1
  template:
    metadata:
      labels:
        owner: minerva-mcgonagall
    spec:
      containers:
        - name: minerva-mcgonagall-client
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
        - name: minerva-mcgonagall-80
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 80"]
        - name: minerva-mcgonagall-8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 8080"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harry-potter
  namespace: gryffindor
spec:
  selector:
    matchLabels:
      owner: harry-potter
  replicas: 2
  template:
    metadata:
      labels:
        owner: harry-potter
    spec:
      containers:
        - name: harry-potter-client
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
        - name: harry-potter-80
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 80"]
        - name: harry-potter-8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 8080"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: draco-malfoy
  namespace: slytherin
spec:
  selector:
    matchLabels:
      owner: draco-malfoy
  replicas: 2
  template:
    metadata:
      labels:
        owner: draco-malfoy
    spec:
      containers:
        - name: draco-malfoy-client
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
        - name: draco-malfoy-80
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 80"]
        - name: draco-malfoy-8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 8080"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: centaurs
  namespace: forbidden-forest
spec:
  selector:
    matchLabels:
      owner: firenze
  replicas: 1
  template:
    metadata:
      labels:
        owner: firenze
    spec:
      containers:
        - name: firenze-client
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
        - name: firenze-80
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 80"]
        - name: firenze-8080
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          command: ["/bin/bash", "-c", "/agnhost serve-hostname --tcp --http=false --port 8080"]
